rootProject.name = 'sophon'

//Commons
include ('sophon-commons:sophon-cache')
include ('sophon-commons:sophon-common')
include ('sophon-commons:sophon-core')
include ('sophon-commons:sophon-crypto')
include ('sophon-commons:sophon-ldap')

include ('sophon-entity')
include ('sophon-persistence')

//sophon-starter
include ('sophon-starter:sophon-starter-captcha')
include ('sophon-starter:sophon-starter-ip2location')
include ('sophon-starter:sophon-starter-otp')
include ('sophon-starter:sophon-starter-sms')
include ('sophon-starter:sophon-starter-social')
include ('sophon-starter:sophon-starter-web')
include ('sophon-starter:sophon-starter-passkey')

//authentications
include ('sophon-authentications:sophon-authentication-core')
include ('sophon-authentications:sophon-authentication-provider')
include ('sophon-authentications:sophon-authentication-provider-mgt')

//rest apis
include ('sophon-web-apis:sophon-web-api-rest')
include ('sophon-web-apis:sophon-web-api-scim')

//synchronizers
include ('sophon-synchronizers:sophon-synchronizer')
include ('sophon-synchronizers:sophon-synchronizer-activedirectory')
include ('sophon-synchronizers:sophon-synchronizer-dingtalk')
include ('sophon-synchronizers:sophon-synchronizer-feishu')
include ('sophon-synchronizers:sophon-synchronizer-jdbc')
include ('sophon-synchronizers:sophon-synchronizer-ldap')
include ('sophon-synchronizers:sophon-synchronizer-workweixin')

//Protocol
include ('sophon-protocols:sophon-protocol-authorize')
include ('sophon-protocols:sophon-protocol-cas')
include ('sophon-protocols:sophon-protocol-extendapi')
include ('sophon-protocols:sophon-protocol-formbased')
include ('sophon-protocols:sophon-protocol-jwt')
include ('sophon-protocols:sophon-protocol-oauth-2.0')
include ('sophon-protocols:sophon-protocol-saml-2.0')
include ('sophon-protocols:sophon-protocol-tokenbased')

//webs
//sophon(sign)
include ('sophon-webs:sophon-web-sophon')
//management(mgt)
include ('sophon-webs:sophon-web-mgt')
//openapi(open)
include ('sophon-webs:sophon-web-openapi')
//gataway
include ('sophon-webs:sophon-gataway')

