# 閰嶇疆鏂囦欢鍔犲瘑鏍瑰瘑�?
jasypt:
  encryptor:
    password: pig
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    
# Spring 鐩稿�?
spring:
  cache:
    type: redis
  redis:
    host: pig-redis
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: pig-sentinel:5003

# 鏆撮湶鐩戞帶绔�?
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS


# feign 閰嶇�?
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# mybaits-plus閰嶇�?
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

# swagger 閰嶇�?
swagger:
  enabled: true
  title: Pig Swagger API
  gateway: http://${GATEWAY_HOST:pig-gateway}:${GATEWAY-PORT:9999}
  token-url: ${swagger.gateway}/auth/oauth2/token
  scope: server
  services:
    pig-upms-biz: admin
    pig-codegen: gen
#cas閰嶇�?
cas:
  #绉橀�?
  key: n0c9MTcwMjIwMjMxNzE2NDMwOTAskV
  server:
    host:
      grant_url: http://sso.Sophon.top/sign/authz/cas
      #cas鏈嶅姟绔湴鍧€ 杩欐槸鎴戠殑cas鏈嶅姟绔湴鍧€ 闇€瑕佷慨鏀规垚浣犱滑鐨刢as鏈嶅姟绔湴鍧€
      url: http://sso.Sophon.top/Sophon/authz/cas
      #cas鏈嶅姟绔櫥褰曞湴鍧�?
      login_url: http://sso.Sophon.top/Sophon/#/passport/login?redirect_uri=aHR0cDovL3Nzby5tYXhrZXkudG9wL3NpZ24vYXV0aHovY2FzLzQxMDY1ZmUzLWFlNjctNDE3Mi1hNDYwLWZkMDA3OWU4ODI5NA
      #cas鏈嶅姟绔櫥鍑哄湴鍧�?service鍙傛暟鍚庨潰璺熷氨鏄渶瑕佽烦杞殑椤甸�?鎺ュ�?杩欓噷鎸囧畾鐨勬槸cas瀹㈡埛绔櫥褰曟帴鍙?
      logout_url: ${cas.server.host.url}/logout?service=${cas.service.host.url}${cas.service.host.login_url}
  service:
    host:
      #cas瀹㈡埛绔湴鍧€
      url: http://localhost:8080
      #cas瀹㈡埛绔湴鍧€鐧诲綍鍦板潃
      login_url: /login
      #cas瀹㈡埛绔湴鍧€鐧诲嚭鍦板潃
      logout_url: /logout    
