buildscript {
	repositories {
		maven { url 'https://maven.aliyun.com/nexus/content/groups/public/'}
	}
	dependencies {
		//springboot jar
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
	id 'java'
	id "io.spring.dependency-management" version "1.0.11.RELEASE"
	id 'org.springframework.boot' version "${springBootVersion}"
}

apply plugin: 'io.spring.dependency-management'

description = "sophon-web-Sophon"

bootJar {
	dependsOn jar
	archiveBaseName = 'sophon-boot'
    version = "${project.version}-ga"
    mainClass = 'org.zeron.sophon.SophonApplication'
	manifest {
	        attributes(
						"Implementation-Title": project.name,
	                	"Implementation-Vendor": project.vendor,
	                	"Created-By": project.author,
	                	"Implementation-Date": java.time.ZonedDateTime.now(),
	                	"Implementation-Version": project.version
	           )
	    }	
}

dependencies {
	implementation project(":sophon-common")
	implementation project(":sophon-core")
	implementation project(":sophon-persistence")
   	
   	implementation project(":sophon-starter:sophon-starter-captcha")
   	implementation project(":sophon-starter:sophon-starter-ip2location")
	implementation project(":sophon-starter:sophon-starter-otp")
	implementation project(":sophon-starter:sophon-starter-sms")
	implementation project(":sophon-starter:sophon-starter-social")
	implementation project(":sophon-starter:sophon-starter-web")
	
   	implementation project(":sophon-authentications:sophon-authentication-core")
   	implementation project(":sophon-authentications:sophon-authentication-provider")

   	implementation project(":sophon-protocols:sophon-protocol-authorize")
   	implementation project(":sophon-protocols:sophon-protocol-cas")
	implementation project(":sophon-protocols:sophon-protocol-extendapi")
	implementation project(":sophon-protocols:sophon-protocol-formbased")
	implementation project(":sophon-protocols:sophon-protocol-tokenbased")
   	implementation project(":sophon-protocols:sophon-protocol-oauth-2.0")
   	implementation project(":sophon-protocols:sophon-protocol-saml-2.0")
	implementation project(":sophon-protocols:sophon-protocol-jwt")
}
