server:
  port: 9001
# 鎺堟潈鏈嶅姟鍦板�?
Sophon-auth-url: http://sso.Sophon.top/sign

security:
  oauth2:
    client:
      client-id: 1000185112135991296
      client-secret: 8Nv7MTcwNjIwMjQyMDU5Mzg5MDU65R
      scope: all
      user-authorization-uri: ${Sophon-auth-url}/authz/oauth/v20/authorize
      access-token-uri: ${Sophon-auth-url}/authz/oauth/v20/token
    resource:
      # 妫€鏌ヤ护鐗?
      #token-info-uri: ${Sophon-auth-url}/authz/oauth/v20/token
      # 鐢ㄦ埛淇℃伅
      user-info-uri: ${Sophon-auth-url}/api/oauth/v20/me

spring:
  main:
    allow-bean-definition-overriding: true
