
description = "sophon-authentication-provider"


dependencies {
	//local jars
	implementation fileTree(dir: '../sophon-lib/', include: '*/*.jar')
	
	implementation project(":sophon-commons:sophon-cache")
	implementation project(":sophon-commons:sophon-common")
	implementation project(":sophon-commons:sophon-core")
	implementation project(":sophon-commons:sophon-crypto")
	implementation project(":sophon-commons:sophon-ldap")
	
	implementation project(":sophon-entity")
	implementation project(":sophon-persistence")
	
	implementation project(":sophon-starter:sophon-starter-ip2location")
	implementation project(":sophon-starter:sophon-starter-otp")
	implementation project(":sophon-starter:sophon-starter-sms")
	
	implementation project(":sophon-authentications:sophon-authentication-core")
   
}
