description = "maxkey-persistence"

// 跳过测试（这些测试需要数据库连接和 Spring 上下文）
test {
    enabled = false
}

dependencies {
	//local jars
	implementation fileTree(dir: '../maxkey-lib/*/', include: '*.jar')
    	
    implementation project(":maxkey-commons:maxkey-common")
    implementation project(":maxkey-commons:maxkey-core")
    implementation project(":maxkey-commons:maxkey-crypto")
    
    implementation project(":maxkey-entity")
}