#Sophon nginx Proxy Server

server {
    listen       80;

    server_name  localhost;
	
	proxy_set_header host $host; # 杞彂璇锋眰鏃跺皢璇锋眰鐨勫煙鍚嶄竴璧疯浆鍙?

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
	
	#鏈嶅姟鍣ㄩ泦缇よ矾寰?
	#璁よ瘉鍚庣
	location /sign/ {
		proxy_pass http://Sophon:9527/sign/;
	}
	
	#璁よ瘉鍓嶇
	location /Sophon/ {
		proxy_pass http://Sophon-frontend:8527/Sophon/;
	}
	
	#绠＄悊鍚庣
	location /Sophon-mgt-api/ {
		proxy_pass http://Sophon-mgt:9526/Sophon-mgt-api/;
	}
	
	#绠＄悊鍓嶇
	location /Sophon-mgt/ {
		proxy_pass http://Sophon-mgt-frontend:8526/Sophon-mgt/;
	}

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
