server:
  port: 8989
cas:
  server-url-prefix: http://iot.intra.zeron.ai:9529/sign/authz/cas/
  server-login-url: http://iot.intra.zeron.ai:9529/sign/authz/cas/login
  client-host-url: http://iot.intra.zeron.ai:8989/
  validation-type: cas
#  拦截的URL地址
  authentication-url-patterns:
    - /test1/index
    - /test1/index1