# 娓╅Θ鎻愮ず锛氫笉寤鸿鐩存帴淇敼姝ゆ枃浠讹紝涓轰簡骞冲彴鍗囩骇鏂逛究锛屽缓璁皢闇€瑕佷慨鏀圭殑鍙傛暟鍊硷紝澶嶅埗鍒癮pplication.yml閲岃繘琛岃鐩栬鍙傛暟鍊笺�?

#Sophon:
#  enabled: true



oauth2:
  # 鐮佷�?
  Sophon:
    clientId: 821060415982141440
    clientSecret: MrjGMDkwMjIwMjMxNTE0MzkxODAv5o
    serverUrl: http://sso.Sophon.top
    redirectUri: http://localhost:8981/js/oauth2/callback/Sophon
    className: com.jeesite.modules.Sophon.oauth.realm.request.AuthSophonJeeGitRequest
  gitee:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/gitee
  # 鑵捐QQ
  qq:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/qq
    unionid: xxxxxx
    
  # 寰俊寮€鏀惧钩�?
  weixin:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/weixin
    
  # 寰俊鍏紬骞冲�?
  weixin_mp:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/weixin_mp
   
  # 浼佷笟寰俊 
  weixin_qy:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/weixin_qy
    agentId: xxxxxx
  # 閽夐�?
  ding_talk:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/ding_talk
  # Github
  github:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/github
  # 鐧惧�?
  baidu:
    clientId: xxxxxx
    clientSecret: xxxxxx
    redirectUri: http://127.0.0.1:8980/js/oauth2/callback/baidu  
